name: dynamic_overflow_menu_bar
description: A widget that creates an overflow menu based on available space
version: 1.0.0
author: thinkdigitalsoftware <jwhite@thinkdigital.software>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

