name: dynamic_overflow_menu_bar
description: A widget that creates an overflow menu based on available space
version: 0.1.2
repository: https://github.com/ThinkDigitalSoftware/dynamic_overflow_menu_bar
homepage: https://github.com/ThinkDigitalSoftware/dynamic_overflow_menu_bar

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

